### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by ghost** [Nikait/ni_bomber#2]
Через несколько удачных сессий работы бомбера, при запуске новой сессии появляется следующее:
```
[*]check number - OK
---------------------------------
|    amount    |      time      |
---------------------------------
1 sms sent!         11:54:11
2 sms sent!         11:54:11
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7c120e4580>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='qlean.ru', port=443): Max retries exceeded with url: /clients-api/v2/sms_codes/auth/request_code (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7c120e4580>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ni_bomber/ni_bomber.py", line 54, in <module>
    services.attack(number, sms)
  File "/data/data/com.termux/files/home/ni_bomber/services.py", line 55, in attack
    requests.post("https://qlean.ru/clients-api/v2/sms_codes/auth/request_code",json = {"phone": number_7})
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='qlean.ru', port=443): Max retries exceeded with url: /clients-api/v2/sms_codes/auth/request_code (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7c120e4580>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```
Как это решить?

**Comment by Nikait** [comment]
Пртвет. Либо у тебя проблемы с интернетом, либо сервер начал блокировать твой ip. А так смотри можешь подредактировать services.py где идёт цикл с запросами и просто вырезаешь этот 3 запрос

**Comment by JustNewNonProgrammer** [comment]
Спасибо!

**Comment by Nikait** [comment]
рад помочь :з
